// Code generated by ifacemaker; DO NOT EDIT.

package route

import (
	"context"
	"github.com/gofiber/fiber/v2"
)

// Method ...
type Method interface {
	MapHandlers(app fiber.Router)
	Create(ctx context.Context, param *Upsert) (any, int, error)
	Get(ctx context.Context, param *Get) (any, int, error)
	Delete(_ context.Context, param *Delete) (any, int, error)
}
